import SwiftUI

enum Language : String, Codable {
    case Arabic     = "ar"
    case Chinese    = "zh"
    case Czech      = "cs"
    case Danish     = "da"
    case Dutch      = "nl"
    case English    = "en"
    case French     = "fr"
    case German     = "de"
    case Greek      = "el"
    case Hebrew     = "he"
    case Hindi      = "hi"
    case Icelandic  = "is"
    case Indonesian = "id"
    case Irish      = "ga"
    case Italian    = "it"
    case Japanese   = "ja"
    case Korean     = "ko"
    case Latin      = "la"
    case Norwegian  = "no"
    case Persian    = "fa"
    case Polish     = "pl"
    case Portuguese = "pt"
    case Russian    = "ru"
    case Spanish    = "es"
    case Swedish    = "sv"
    case Tagalog    = "tl"
    case Tahitian   = "ty"
    case Thai       = "th"
    case Turkish    = "tr"
}
